#!/bin/bash
/home/cizaquita/Desktop/ada_resco_api/.venv/bin/python manage.py runserver ada.resistencia.la:1338

